version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: road-detector-postgres-dev
    environment:
      POSTGRES_DB: road_detector
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d road_detector"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - road-detector-dev-network

volumes:
  postgres_dev_data:

networks:
  road-detector-dev-network:
    driver: bridge 